nodejs:
  applicationPort: 3100
  aadIdentityName: fact
  keyVaults:
    fact:
      resourceGroup: fact
      secrets:
        - AppInsightsInstrumentationKey
  ingressHost: fact.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/fact/frontend:latest'
  environment:
    FACT_API_URL: "http://fact-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
