apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ctf-frontend App
name: ctf-frontend
home: https://github.com/hmcts/ctf-frontend
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.0.1
    repository: '@hmctspublic'

