services:
  frontend:
    url: FRONTEND_URL
  api:
    url: FACT_API_URL
  image-store:
    url: IMAGE_BASE_URL
  admin-portal:
    url: ADMIN_PORTAL_URL
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
