app:
  useCSRFProtection: 'true'
  security:
    referrerPolicy: 'origin'
services:
  frontend:
    name: 'FACT Frontend'
    url: 'http://localhost:3100'
  api:
    name: 'FACT API'
    url: 'http://localhost:8080'
  image-store:
    name: 'Image Store'
    url: 'https://factaat.blob.core.windows.net/images'
health:
  timeout: 5000
  deadline: 15000
